export const REQUEST_CURRENT_WEEK = 'REQUEST_CURRENT_WEEK';
export const RECEIVE_CURRENT_WEEK = 'RECEIVE_CURRENT_WEEK';
export const REQUEST_NEXT_WEEK = 'REQUEST_NEXT_WEEK';
export const RECEIVE_NEXT_WEEK = 'RECEIVE_NEXT_WEEK';